use master 
GO
IF DB_ID('QLSieuThiMiNi') is not null
	Drop Database QLSieuThiMiNi
Go
Create Database QLSieuThiMiNi
GO
use QLSieuThiMiNi
GO

CREATE TABLE SANPHAM
(
	MaSP int IDENTITY(1,1),
	TenSP nvarchar(50),
	MaLoaiSP int,
	GiaMuaVao decimal(18,2),
	GiaBanRa decimal(18,2),
	SoLuong int,
	KhuyenMai int,
	KichHoat bit DEFAULT(1)
	CONSTRAINT PK_SANPHAM
	PRIMARY KEY (MaSP)
)

CREATE TABLE LOAISANPHAM
(
	MaLoaiSP int IDENTITY(1,1),
	TenLoaiSP nvarchar(50),
	KichHoat bit DEFAULT(1)
	CONSTRAINT PK_LOAISANPHAM
	PRIMARY KEY (MaLoaiSp)
)

CREATE TABLE HOADON
(
	MaHD int IDENTITY(1,1),
	MaNV int,
	MaKH int,
	NgayLapHD datetime,
	DiemThuong int,
	ThanhTien decimal(18,2)
	CONSTRAINT PK_HOADON
	PRIMARY KEY (MaHD)
)

CREATE TABLE CHITIETHOADON
(
	Id int IDENTITY(1,1),
	MaHD int,
	MaSP int,
	SoLuong int, 
	DonGia decimal(18,2),
	ThanhTien decimal(18,2),
	Discount decimal(18,2),
	TienVon decimal(18,2)
	CONSTRAINT PK_CHITIETHOADON
	PRIMARY KEY (Id)
)

CREATE TABLE KHACHHANG
(
	MaKH int IDENTITY(0,1),
	TenKH nvarchar(50),
	SoDienThoai varchar(50),
	DiaChi nvarchar(50),
	NgayLapThe datetime,
	DiemThuongTichLuy int,
	NgayMuaGanNhat datetime,
	CONSTRAINT PK_KHACHHANG
	PRIMARY KEY (MaKH)
)

CREATE TABLE NHANVIEN
(
	MaNV int IDENTITY(2000,1),
	TenNV nvarchar(50),
	NgaySinh datetime,
	SoDienThoai varchar(50),
	QueQuan nvarchar(50),
	GioiTinh bit,
	MaChucVu int,
	MatKhau nvarchar(50),
	KichHoat bit DEFAULT(1)
	CONSTRAINT PK_NHANVIEN
	PRIMARY KEY (MaNV)
)

CREATE TABLE CHUCVU
(
	MaChucVu int IDENTITY(1,1),
	TenChucVu nvarchar(50),
	CONSTRAINT PK_CHUCVU
	PRIMARY KEY (MaChucVu)
)

CREATE TABLE THANHTOAN
(
	MaThanhToan int IDENTITY(1,1),
	MaHD int,
	MaHinhThucTT int,
	ThanhTien decimal(18,2),
	NgayThanhToan datetime,
	CONSTRAINT PK_THANHTOAN
	PRIMARY KEY (MaThanhToan)
)

CREATE TABLE HINHTHUCTHANHTOAN
(
	MaHinhThucTT int,
	TenHinhThucTT nvarchar(50),
	CONSTRAINT PK_HINHTHUCTHANHTOAN
	PRIMARY KEY (MaHinhThucTT)
)

CREATE TABLE KIEMKEKHO
( 
	Id int IDENTITY(1,1),
	MaKiemKe int,
	MaNV int,
	MaSP int,
	NgayKTKho datetime,
	SoLuongTonKho int,
	SoLuongTonQuay int,
	SoLuongChenhLech int,
	CONSTRAINT PK_KIEMKEKHO
	PRIMARY KEY (Id)
)

CREATE TABLE PHANCA
(
	MaPhanCa int IDENTITY(1,1),
	MaNV int,
	NgayLam datetime,
	Ca int
	CONSTRAINT PK_PHANCA
	PRIMARY KEY (MaPhanCa)
)

CREATE TABLE PHIEUNHAPHANG
(	
	MaPhieuNhapHang int IDENTITY(1,1),
	MaNV int,
	NgayLapPhieu datetime,
	NgayNhapHang datetime,
	TongTien decimal(18,2),
	TrangThai int,
	MaNCC int
	CONSTRAINT PK_PHIEUNHAPHANG
	PRIMARY KEY (MaPhieuNhapHang)
)

CREATE TABLE CHITIETPHIEUNHAPHANG
(
	Id int IDENTITY(1,1),
	MaPhieuNhapHang int,
	MaSP int,
	SoLuong int,
	DonGia decimal(18,2), 
	ThanhTien decimal(18,2)
	CONSTRAINT PK_CHITIETPHIEUNHAPHANG
	PRIMARY KEY (Id)
)

CREATE TABLE NHACUNGCAP
(
	MaNCC int IDENTITY(1,1),
	TenNCC nvarchar(50),
	KichHoat bit DEFAULT(1)
	CONSTRAINT PK_NHACUNGCAP
	PRIMARY KEY (MaNCC)
)

CREATE TABLE NCC_SP
(
	Id int IDENTITY(1,1),
	MaSP int,
	MaNCC int,
	KichHoat bit DEFAULT(1)
	CONSTRAINT PK_NCC_SP
	PRIMARY KEY (Id)
)

CREATE TABLE CALAM
(
	Id int IDENTITY(1,1),
	SoCa nvarchar(50)
	CONSTRAINT PK_CALAM
	PRIMARY KEY (Id)
)

ALTER TABLE SANPHAM
ADD 
CONSTRAINT FK_SANPHAM_LOAISANPHAM
FOREIGN KEY (MaLoaiSP)
REFERENCES LOAISANPHAM(MaLoaiSP)

ALTER TABLE HOADON
ADD 
CONSTRAINT FK_HOADON_NHAVIEN
FOREIGN KEY (MaNV)
REFERENCES NHANVIEN(MaNV),
CONSTRAINT FK_HOADON_KHACHHANG
FOREIGN KEY (MaKH)
REFERENCES KHACHHANG(MaKH)

ALTER TABLE NHANVIEN
ADD 
CONSTRAINT FK_NHANVIEN_CHUCVU
FOREIGN KEY (MaChucVu)
REFERENCES CHUCVU(MaChucVu)

ALTER TABLE THANHTOAN
ADD 
CONSTRAINT FK_THANHTOAN_HOADON
FOREIGN KEY (MaHD)
REFERENCES HOADON(MaHD),
CONSTRAINT FK_THANHTOAN_HINHTHUCTHANHTOAN
FOREIGN KEY (MaHinhThucTT)
REFERENCES HINHTHUCTHANHTOAN(MaHinhThucTT)

ALTER TABLE KIEMKEKHO
ADD 
CONSTRAINT FK_KIEMKEKHO_NHANVIEN
FOREIGN KEY (MaNV)
REFERENCES NHANVIEN(MaNV),
CONSTRAINT FK_KIEMKEKHO_SANPHAM
FOREIGN KEY (MaSP)
REFERENCES SANPHAM(MaSP)

ALTER TABLE PHIEUNHAPHANG
ADD 
CONSTRAINT FK_PHIEUNHAPHANG_NHANVIEN
FOREIGN KEY (MaNV)
REFERENCES NHANVIEN(MaNV),
CONSTRAINT FK_PHIEUNHAPHANG_NHACUNGCAP
FOREIGN KEY (MaNCC)
REFERENCES NHACUNGCAP(MaNCC)

ALTER TABLE PHANCA
ADD 
CONSTRAINT FK_PHANCA_NHANVIEN
FOREIGN KEY (MaNV)
REFERENCES NHANVIEN(MaNV)

ALTER TABLE CHITIETPHIEUNHAPHANG
ADD 
CONSTRAINT FK_CHITIETPHIEUNHAPHANG_SANPHAM
FOREIGN KEY (MaSP)
REFERENCES SANPHAM(MaSP),
CONSTRAINT FK_CHITIETPHIEUNHAPHANG_PHIEUNHAPHANG
FOREIGN KEY (MaPhieuNhapHang)
REFERENCES PHIEUNHAPHANG(MaPhieuNhapHang)

ALTER TABLE CHITIETHOADON
ADD 
CONSTRAINT FK_CHITIETHOADON_SANPHAM
FOREIGN KEY (MaSP)
REFERENCES SANPHAM(MaSP),
CONSTRAINT FK_CHITIETHOADON_HOADON
FOREIGN KEY (MaHD)
REFERENCES HOADON(MaHD)

ALTER TABLE PHANCA
ADD
CONSTRAINT FK_PHANCA_CALAM
FOREIGN KEY (Ca)
REFERENCES CALAM(Id)

ALTER TABLE NCC_SP
ADD
CONSTRAINT FK_NCC_SP_SANPHAM
FOREIGN KEY (MaSP)
REFERENCES SANPHAM(MaSP),
CONSTRAINT FK_NCC_SP_NHACUNGCAP
FOREIGN KEY (MaNCC)
REFERENCES NHACUNGCAP(MaNCC)

Set dateformat 'dmy' 


Insert into CHUCVU values (N'Admin'),
						  (N'Quản Lý'),
						  (N'Thu Ngân'),
						  (N'Nhân Viên Kho')

Insert into CALAM Values(N'Ca 1'),
						(N'Ca 2'),
						(N'Ca 3'),
						(N'Ca 4'),
						(N'Off')

Insert into KHACHHANG(TenKH) VALUES (N'Khách Vãng Lai')

Insert into HINHTHUCTHANHTOAN VALUES (1,N'Tiền Mặt Cash'),
									 (2,N'Thẻ Visa/Mastercard')

Insert into NHANVIEN (TenNV,MaChucVu,MatKhau) Values ('Admin',1,'123456')
