//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIEMKEKHO
    {
        public int Id { get; set; }
        public Nullable<int> MaKiemKe { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<System.DateTime> NgayKTKho { get; set; }
        public Nullable<int> SoLuongTonKho { get; set; }
        public Nullable<int> SoLuongTonQuay { get; set; }
        public Nullable<int> SoLuongChenhLech { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
