//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCC_SP
    {
        public int Id { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<bool> KichHoat { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
